# Generated by Django 6.0 on 2025-12-18 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('future_scope', models.TextField()),
                ('salary_range', models.CharField(max_length=100)),
                ('recommended_courses', models.TextField(help_text='Comma separated course names or links')),
                ('work_type', models.CharField(choices=[('Office', 'Office'), ('Remote', 'Remote'), ('Field', 'Field'), ('Research', 'Research')], default='Office', max_length=50)),
                ('interests', models.ManyToManyField(related_name='careers', to='recommender.interest')),
                ('skills', models.ManyToManyField(related_name='careers', to='recommender.skill')),
            ],
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(max_length=100)),
                ('preferred_work_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_careers', models.ManyToManyField(to='recommender.career')),
                ('selected_interests', models.ManyToManyField(to='recommender.interest')),
                ('selected_skills', models.ManyToManyField(to='recommender.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
