# Generated by Django 6.0 on 2025-12-18 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='skills',
        ),
        migrations.AddField(
            model_name='career',
            name='creativity_level',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='career',
            name='leadership_interest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='career',
            name='stress_tolerance',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='career',
            name='work_style',
            field=models.CharField(choices=[('Team', 'Team'), ('Solo', 'Solo')], default='Team', max_length=50),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='feedback_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrecommendation',
            name='results_json',
            field=models.TextField(blank=True, help_text='Stored scoring, reasoning and gap analysis'),
        ),
        migrations.CreateModel(
            name='CareerRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='recommender.career')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommender.userrecommendation')),
            ],
        ),
        migrations.CreateModel(
            name='CareerSkillWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.career')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.skill')),
            ],
            options={
                'unique_together': {('career', 'skill')},
            },
        ),
    ]
