# Generated by Django 6.0 on 2025-12-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_remove_career_skills_career_creativity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='skills',
            field=models.ManyToManyField(related_name='careers', through='recommender.CareerSkillWeight', to='recommender.skill'),
        ),
    ]
