# Generated by Django 6.0 on 2025-12-19 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_career_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Business', 'Business'), ('Medical', 'Medical'), ('Arts', 'Arts'), ('Government', 'Government')], max_length=50)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('what_you_will_learn', models.TextField(help_text='One learning point per line')),
                ('prerequisites', models.TextField(blank=True, help_text='One prerequisite per line')),
                ('recommended_background', models.TextField(blank=True)),
                ('tools_covered', models.CharField(help_text='Comma separated tools', max_length=255)),
                ('related_careers', models.ManyToManyField(related_name='courses', to='recommender.career')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recommender.course')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
